### ISSUE TITLE
Support debug build options

### ISSUE THREAD

**Issue by tobifalk** [eclipse/cloe#14]
Currently, it is not straightforward to build and deploy packages with debug options. For the build, the `CONAN_OPTIONS` variable could be used like so:

`make CONAN_OPTIONS="-s build_type=Debug" export  package`

However, depending on which make targets are being used, all dependencies might be rebuilt with debug options as well. Some documentation or a dedicated make target would be desirable.

For the package deployment with the cli, the build type would need to be passed to `cloe-launch` (e.g. via the `CONAN_OPTIONS` variable).

**Comment by cassava** [comment]
The current best practice to achieve this is to use Conan profiles.

For an example, see the files in `dist/conan`, where debug build type is applied to all packages matching `cloe/develop` user-channel:

```
include(default)

[settings]
build_type=RelWithDebInfo
*/*@cloe/develop:build_type=Debug
```
