### ISSUE TITLE
VTD start script fails when symlinking the VTD setups

### ISSUE THREAD

**Issue by clssn** [eclipse/cloe#18]
## Issue Description
Due to the heavy use of links within VTD setups and implications in symlinks pointing to parent directories, 
the default way Cloe's VTD start script arranges the 'VTD facades' fails with:
`[cloe] Error configuring simulator vtd: timeout waiting for SCP message`

## Expected Behavior
Once Cloe is built including the VTD packages, VTD related smoke tests should succeed.

## Steps to Reproduce
This can be reproduced by building Cloe and running VTD tests like this:
```
WITH_VTD=1 make export package
bats tests/test_vtd.bats
```

**Comment by clssn** [comment]
Thanks @tobifalk for pointing out that this can be quick-fixed adding a `--copy-setup` argument to the VTD start command in `tests/bootstrap_vtd.json`. In my opinion, we should remove the symlink option for setups. Or do you see any use-case for using symlinks here at all? You @cassava ?

**Comment by tobifalk** [comment]
I think the hope was that by using symlinks we may get a performance benefit for larger setups. If this conflicts with the way vtd works, we should at least consider changing the default to `--copy-setup`.

**Comment by cassava** [comment]
Currently, we are creating a new facade for every smoketest run... so my goal was indeed to have the facade creation work as quickly as possible.

**Comment by clssn** [comment]
Yes, but that doesn't work with VTD because they use symlinks to `../../../something` in all setups.
So copy setups and link projects was my proposal from above. And remove the options. Agreed?
